server:
  port: 8080
  tomcat:
    max-part-count: 30

file:
  upload-dir: uploads/

spring:
  application:
    name: algoQuestSV
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/algoquest?stringtype=unspecified
    username: postgres
    password: June1996@
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
        show-sql: true
  sql:
    init:
      platform: postgres
